load("//build/bazel_common_rules/dist:dist.bzl", "copy_to_dist_dir")
load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

def define_modules(target, variant):
    kernel_build_variant = "{}_{}".format(target, variant)

    #The below will take care of the defconfig
    include_defconfig = ":{}_defconfig".format(variant)

    mod_list = []

    ddk_module(
        name = "{}_ecm".format(kernel_build_variant),
        out = "ecm.ko",
        srcs = [
            "ecm_classifier_pcc.c",
            "ecm_classifier_dscp.c",
            "frontends/cmn/ecm_ae_classifier.c",
            "frontends/cmn/ecm_ipv4.c",
            "frontends/cmn/ecm_ported_ipv4.c",
            "frontends/cmn/ecm_stats_v4.c",
            "ecm_tracker_udp.c",
            "ecm_tracker_tcp.c",
            "ecm_tracker_datagram.c",
            "ecm_tracker.c",
            "frontends/ecm_front_end_ipv4.c",
            "frontends/ecm_front_end_common.c",
            "ecm_db/ecm_db.c",
            "ecm_db/ecm_db_connection.c",
            "ecm_db/ecm_db_mapping.c",
            "ecm_db/ecm_db_host.c",
            "ecm_db/ecm_db_node.c",
            "ecm_db/ecm_db_iface.c",
            "ecm_db/ecm_db_listener.c",
            "ecm_db/ecm_db_timer.c",
            "ecm_classifier.c",
            "ecm_classifier_default.c",
            "ecm_interface.c",
            "ecm_conntrack_notifier.c",
            "ecm_init.c",
            "ecm_notifier.c",
            "ecm_state.c",
            "frontends/ecm_front_end_ipv6.c",
            "frontends/cmn/ecm_ipv6.c",
            "frontends/cmn/ecm_ported_ipv6.c",
            "frontends/cmn/ecm_stats_v6.c",
            "frontends/sfe/ecm_sfe_common.c",
            "frontends/sfe/ecm_sfe_ipv4.c",
            "frontends/sfe/ecm_sfe_ported_ipv4.c",
            "frontends/sfe/ecm_sfe_stats_v4.c",
            "frontends/sfe/ecm_sfe_ported_ipv6.c",
            "frontends/sfe/ecm_sfe_ipv6.c",
            "frontends/sfe/ecm_sfe_stats_v6.c",
        ],
        kernel_build = "//msm-kernel:{}-defconfig".format(kernel_build_variant),
        copts = [
            "-DECM_CLASSIFIER_PCC_ENABLE=y",
            "-DECM_INTERFACE_RAWIP_ENABLE=y",
            "-DECM_INTERFACE_RAWIP_ENABLE=y",
            "-DECM_TRACKER_DPI_SUPPORT_ENABLE=y",
            "-DECM_CLASSIFIER_DSCP_ENABLE=y",
            "-DECM_INTERFACE_VLAN_ENABLE=y",
            "-DECM_BRIDGE_VLAN_FILTERING_ENABLE=y",
            "-DECM_BAND_STEERING_ENABLE=y",
            "-DECM_DB_CTA_TRACK_ENABLE=y",
            "-DECM_DB_ADVANCED_STATS_ENABLE=y",
            "-DECM_FRONT_END_CONN_LIMIT_ENABLE=y",
            "-DECM_FRONT_END_SFE_ENABLE=y",
            "-DECM_STATE_OUTPUT_ENABLE=y",
            "-DECM_DB_XREF_ENABLE=y",
            "-DECM_IPV6_ENABLE=y",
            "-DECM_CLASSIFIER_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_OVS_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_MARK_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_DSCP_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_HYFI_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_PCC_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_NL_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_EMESH_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_MSCS_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_DEFAULT_DEBUG_LEVEL=1",
            "-DECM_DB_DEBUG_LEVEL=1",
            "-DECM_INIT_DEBUG_LEVEL=3",
            "-DECM_FRONT_END_IPV4_DEBUG_LEVEL=1",
            "-DECM_FRONT_END_IPV6_DEBUG_LEVEL=1",
            "-DECM_FRONT_END_COMMON_DEBUG_LEVEL=1",
            "-DECM_CMN_IPV4_DEBUG_LEVEL=1",
            "-DECM_CMN_IPV6_DEBUG_LEVEL=1",
            "-DECM_CMN_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_CMN_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_CMN_NON_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_CMN_NON_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_CMN_MULTICAST_IPV4_DEBUG_LEVEL=1",
            "-DECM_CMN_MULTICAST_IPV6_DEBUG_LEVEL=1",
            "-DECM_NSS_COMMON_DEBUG_LEVEL=1",
            "-DECM_NSS_IPV4_DEBUG_LEVEL=1",
            "-DECM_NSS_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_NSS_NON_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_NSS_MULTICAST_IPV4_DEBUG_LEVEL=1",
            "-DECM_NSS_IPV6_DEBUG_LEVEL=1",
            "-DECM_NSS_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_NSS_NON_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_NSS_MULTICAST_IPV6_DEBUG_LEVEL=1",
            "-DECM_SFE_COMMON_DEBUG_LEVEL=1",
            "-DECM_SFE_IPV4_DEBUG_LEVEL=1",
            "-DECM_SFE_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_SFE_NON_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_SFE_MULTICAST_IPV4_DEBUG_LEVEL=1",
            "-DECM_SFE_IPV6_DEBUG_LEVEL=1",
            "-DECM_SFE_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_SFE_NON_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_SFE_MULTICAST_IPV6_DEBUG_LEVEL=1",
            "-DECM_PPE_COMMON_DEBUG_LEVEL=1",
            "-DECM_PPE_IPV4_DEBUG_LEVEL=1",
            "-DECM_PPE_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_PPE_NON_PORTED_IPV4_DEBUG_LEVEL=1",
            "-DECM_PPE_IPV6_DEBUG_LEVEL=1",
            "-DECM_PPE_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_PPE_NON_PORTED_IPV6_DEBUG_LEVEL=1",
            "-DECM_CONNTRACK_NOTIFIER_DEBUG_LEVEL=1",
            "-DECM_TRACKER_DEBUG_LEVEL=1",
            "-DECM_TRACKER_DATAGRAM_DEBUG_LEVEL=1",
            "-DECM_TRACKER_TCP_DEBUG_LEVEL=1",
            "-DECM_TRACKER_UDP_DEBUG_LEVEL=1",
            "-DECM_BOND_NOTIFIER_DEBUG_LEVEL=1",
            "-DECM_INTERFACE_DEBUG_LEVEL=1",
            "-DECM_STATE_DEBUG_LEVEL=1",
            "-DECM_OPENWRT_SUPPORT=1",
            "-DECM_NOTIFIER_DEBUG_LEVEL=1",
            "-DECM_AE_CLASSIFIER_DEBUG_LEVEL=1",
            "-DECM_STATS_DEBUG_LEVEL=1",
            "-DECM_CLASSIFIER_WIFI_DEBUG_LEVEL=1",
            "-DECM_SFE_STATS_DEBUG_LEVEL=1",
            "-DECM_PPE_STATS_DEBUG_LEVEL=1",
        ],
        deps = [
            ":ecm_headers",
            "//msm-kernel:all_headers",
            "//build_dir/target-aarch64_cortex-a53_musl/linux-sdx85/qca-nss-sfe-1.0:{}-defconfig_qca_nss_sfe".format(kernel_build_variant),
        ],
    )
    mod_list.append("{}_ecm".format(kernel_build_variant))

    ddk_module(
        name = "{}_ecm_ae_select".format(kernel_build_variant),
        out = "ecm_ae_select.ko",
        srcs = [
            "examples/ecm_ae_select.c",
        ],
        kernel_build = "//msm-kernel:{}-defconfig".format(kernel_build_variant),
        copts = [
            "-DECM_AE_CLASSIFIER_DEBUG_LEVEL=1",
            "-Iecm/exports",
        ],
        deps = [
            ":ecm_headers",
            "//msm-kernel:all_headers",
            "{}_ecm".format(kernel_build_variant),
        ],
    )
    mod_list.append("{}_ecm_ae_select".format(kernel_build_variant))

    copy_to_dist_dir(
        name = "{}-defconfig_qca_nss_ecm_dist".format(kernel_build_variant),
        data = mod_list,
        dist_dir = "out/target/product/{}/dlkm/lib/modules/".format(target),
        flat = True,
        wipe_dist_dir = False,
        allow_duplicate_filenames = False,
        mode_overrides = {"**/*": "644"},
        log = "info",
    )
